# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialblood', '0003_auto_20161001_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
    ]
